function [loss] = assembly_loss_at_frequencies(frequency_in_GHz, ...
                                      length_in_inches, ...
                                      physical_constants)
% How to Set physical_constants
% physical_constants(1) = root_constant
% physical_constants(2) = linear_constant
% physical_constants(3) = connector_1_constant
% physical_constants(4) = connector_2_constant

    loss = ...
        ( ( length_in_inches / 12 ) * ...
            (    ( physical_constants(1) * sqrt(frequency_in_GHz) ) + ...
                 ( physical_constants(2) * frequency_in_GHz ) ...
            ) ....
        ) + ...
        ( physical_constants(3) * sqrt(frequency_in_GHz) ) + ...
        ( physical_constants(4) * sqrt(frequency_in_GHz) );
end