function [coefficients]=BLS(mixed,Order,current,desired)

voltage_in=current;
if mixed
	switch Order
		case 0
			error(1)=1;
		case 1
			VP_1=[voltage_in];
		case 2
			VP_1=[voltage_in;(abs(voltage_in).^2)];
		case 3
			VP_1=[voltage_in;(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^2)];
		case 4
			VP_1=[voltage_in;(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^2);(abs(voltage_in).^4)];
		case 5
			VP_1=[voltage_in;(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^2);(abs(voltage_in).^4);...
				voltage_in.*(abs(voltage_in).^4)];
		case 6
			VP_1=[voltage_in;(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^2);(abs(voltage_in).^4);...
				voltage_in.*(abs(voltage_in).^4);(abs(voltage_in).^6)];
		case 7
			VP_1=[voltage_in;(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^2);(abs(voltage_in).^4);...
				voltage_in.*(abs(voltage_in).^4);(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^6)];
		case 8
			VP_1=[voltage_in;(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^2);(abs(voltage_in).^4);...
				voltage_in.*(abs(voltage_in).^4);(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^6);(abs(voltage_in).^8)];
		case 9
			VP_1=[voltage_in;(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^2);(abs(voltage_in).^4);...
				voltage_in.*(abs(voltage_in).^4);(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^6);(abs(voltage_in).^8);...
				voltage_in.*(abs(voltage_in).^8)];
		otherwise
			error(1)=1;
	end
else
	switch Order
		case 0
			error(1)=1;
		case 1
			VP_1=[voltage_in];
		case 2
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2)];
		case 3
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^4)];
		case 4
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^4);voltage_in.*(abs(voltage_in).^6)];
		case 5
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^4);voltage_in.*(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^8)];
		case 6
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^4);voltage_in.*(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^8);voltage_in.*(abs(voltage_in).^10)]; 
		case 7
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^4);voltage_in.*(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^8);voltage_in.*(abs(voltage_in).^10);...
				voltage_in.*(abs(voltage_in).^12)];
		case 8
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^4);voltage_in.*(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^8);voltage_in.*(abs(voltage_in).^10);...
				voltage_in.*(abs(voltage_in).^12);voltage_in.*(abs(voltage_in).^14)];
		case 9
			VP_1=[voltage_in;voltage_in.*(abs(voltage_in).^2);...
				voltage_in.*(abs(voltage_in).^4);voltage_in.*(abs(voltage_in).^6);...
				voltage_in.*(abs(voltage_in).^8);voltage_in.*(abs(voltage_in).^10);...
				voltage_in.*(abs(voltage_in).^12);voltage_in.*(abs(voltage_in).^14);...
				voltage_in.*(abs(voltage_in).^16)];    			
		otherwise
			error(1)=1;
	end	
end

VP_1=VP_1.';
coefficients=(inv(transpose(VP_1)*VP_1)*transpose(VP_1)*desired.').';